/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import static Clases.DatosMateriales.ReporteDonacionesFiltradas;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josei
 */
public class DonacionesFiltradas extends javax.swing.JFrame {

    /**
     * Creates new form DonacionesFiltradas
     */
    public DonacionesFiltradas() {
        initComponents();
        addRowToJTableFiltro();
    }
    public class Donacion
    {
        public String Nombre;
        public String Material;
        public String Fecha;
        public String Peso;
        public String Descripcion;
        public String Evento;
        public Donacion(String Nombre,String Material,String Fecha,String Peso,String Descripcion,String Evento)
        {
            this.Nombre = Nombre;
            this.Material = Material;
            this.Fecha = Fecha;
            this.Peso = Peso;
            this.Descripcion = Descripcion;
            this.Evento = Evento;
                    
        }
        
    }
public ArrayList ListaDonacionesF()
    {
        ArrayList<Donacion> DonacionesList = new ArrayList<Donacion>();
        for (String Linea : ReporteDonacionesFiltradas)
        {
            String[] Valores = Linea.split("\\|");
            Donacion Valor = new Donacion(Valores[0],Valores[1],Valores[2],Valores[3],Valores[4],Valores[5]);
            DonacionesList.add(Valor);
        }
        return DonacionesList;
    }
    public void addRowToJTableFiltro()
    {
        DefaultTableModel model = (DefaultTableModel) jDonacion.getModel();
        ArrayList<Donacion> list = ListaDonacionesF();
        
        Object rowData[] = new Object[6];
        for(int i = 0; i < list.size(); i++)
        {
            rowData[0] = list.get(i).Nombre;
            rowData[1] = list.get(i).Material;
            rowData[2] = list.get(i).Fecha;
            rowData[3] = list.get(i).Peso;
            rowData[4] = list.get(i).Descripcion;
            rowData[5] = list.get(i).Evento;
            model.addRow(rowData);
        }
                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jDonacion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDonacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Material", "Fecha", "Peso", "Descripcion", "Title 6"
            }
        ));
        jScrollPane1.setViewportView(jDonacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 331, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
DefaultTableModel model;
    String Usuario = "";
    String Material = "";
    String Fecha = "";
    String Peso = "";
    String Descripcion = "";
    String Evento="";
    public void AgregarEncabezados() {
        model = (DefaultTableModel) jDonacion.getModel();
        Object[] newIdentifiers = new Object[]{"Usuario", "Material", "Fecha", "Peso", "Descripcion","Evento"};
        model.setColumnIdentifiers(newIdentifiers);
        jDonacion.setFillsViewportHeight(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonacionesFiltradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonacionesFiltradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonacionesFiltradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonacionesFiltradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonacionesFiltradas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jDonacion;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
