/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import static Clases.DatosUsuario.DatosList;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collections;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author josei
 */
public class HacerDonación extends javax.swing.JFrame {

    /**
     * Creates new form HacerDonación
     */
    public HacerDonación() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfDescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taEvento = new javax.swing.JTextArea();
        jcMateriales = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tfPeso = new javax.swing.JTextField();
        btDonar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Hacer Donaciones");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Material:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Descripción:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Evento:");

        tfDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        taEvento.setColumns(20);
        taEvento.setRows(5);
        jScrollPane1.setViewportView(taEvento);

        jcMateriales.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Peso:");

        tfPeso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btDonar.setText("Donar");
        btDonar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btDonarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                                    .addComponent(jcMateriales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                .addComponent(btDonar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jcMateriales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btDonar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String linealeida1="";
        ArrayList<String> Opciones = new ArrayList<String>();
        try { //Se busca al usuario ingresado en el archivo de texto
                FileReader BitacoraMateriales = new FileReader("C:/MEIA/materiales_bitacora.txt");
                BufferedReader MaterialesBitacora = new BufferedReader(BitacoraMateriales);
                while (((linealeida1 = MaterialesBitacora.readLine()) != null)) 
                {   
                    String [] ExtraerMaterial = linealeida1.split("\\|");
                    Opciones.add(ExtraerMaterial[0]);
                }
                MaterialesBitacora.close();
                BitacoraMateriales.close();
                FileReader Materiales = new FileReader("C:/MEIA/materiales.txt");
                BufferedReader Materialestxt = new BufferedReader(Materiales);
                while (((linealeida1 = Materialestxt.readLine()) != null)) 
                {   
                    String [] ExtraerMaterial = linealeida1.split("\\|");
                    Opciones.add(ExtraerMaterial[0]);
                }
                Materialestxt.close();
                Materiales.close();
                
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        for(String mat : Opciones)
        {
            this.jcMateriales.addItem(mat);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btDonarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btDonarMouseClicked
        String Material = String.valueOf(jcMateriales.getSelectedItem());
        String Descripcion = tfDescripcion.getText();
        String Peso = tfPeso.getText();
        String Evento = taEvento.getText();
        Calendar FechaTransaccion = Calendar.getInstance();
        int Anio = FechaTransaccion.get(Calendar.YEAR);
        int Mes = FechaTransaccion.get(Calendar.MONTH);
        int Dia = FechaTransaccion.get(Calendar.DAY_OF_MONTH);
        int Hora = FechaTransaccion.get(Calendar.HOUR_OF_DAY);
        int Minuto = FechaTransaccion.get(Calendar.MINUTE);
        int Segundo = FechaTransaccion.get(Calendar.SECOND);
        String FechaBack = String.valueOf(Dia +"/"+Mes+"/"+ Anio+" "+Hora+":"+Minuto+":"+Segundo);
        HacerNuevaDonacion(DatosList[0],Material,FechaBack,Peso,Descripcion,Evento,DatosList[0],FechaBack);
        ActualizarDescriptores();
    }//GEN-LAST:event_btDonarMouseClicked
    public void HacerNuevaDonacion(String usuario,String material,String fecha,String Peso, String descripcion, String evento, String usuariologueado, String fechaActual)
    {
        String nuevoRgistroDonacion = usuario +"|"+ material+"|"+fecha+"|"+ Peso +"|"+ descripcion +"|"+evento+"|"+usuariologueado+"|"+fechaActual+"|"+1;
        String llave = usuario +","+ material+","+fecha;
        if (!Encontrado(usuario, material, fecha)) {
            String direccion = InsertarIndexadoMaster(nuevoRgistroDonacion, 3);
            InsertarIndexadoIndex(llave, direccion);
        }
    }
    
    public boolean Encontrado(String usuario, String material, String fecha)
    {
        boolean resultado = false;
        boolean usuarioencontrado = false;
        boolean materialencontrado = false;
        boolean fechaencontrada = false;
        ArrayList<String> lista = new ArrayList<>();
        String ruta = "C:\\MEIA\\DonacionIndex.txt";
        String linea = "";
        File f = new File(ruta);
        try{
            if (!f.exists()) {
                f.createNewFile();
            }
            FileReader fr = new FileReader(ruta);
            BufferedReader br = new BufferedReader(fr);
            linea = br.readLine();
            while(!linea.equals("")){
                lista.add(linea);
                linea = br.readLine();
            }
            for(String x : lista)
            {
                if(x.contains(usuario)){
                    usuarioencontrado = true;
                }
            }
            if (usuarioencontrado) {
                for(String x : lista)
                {
                    if(x.contains(usuario+","+material)){
                        materialencontrado = true;
                    }
                }
            }
            if (materialencontrado){
                for(String x : lista)
                {
                    if(x.contains(usuario+","+material+","+fecha)){
                        fechaencontrada = true;
                    }
                }
            }
            if (fechaencontrada){
                resultado = true;
            }
        }catch(IOException ex){
            Logger.getLogger(HacerDonación.class.getName()).log(Level.SEVERE, null, ex);
        }
        return  resultado;
    }
    
    public String InsertarIndexadoMaster(String LineaInsertar,int MaxLineas)
    {
        boolean Escrito = false;
        int Bloque = 1;
        int IndiceLinea = 1;
        String ext = ".txt";
        String inicio = "C:\\MEIA\\Donacion_";
        String ruta = inicio + Bloque + ext;
        String linea = "";
        String direccion = "";
        ArrayList<String> lista = new ArrayList<>();
        try {
        while (!Escrito) {
            File f = new File(ruta);
            if (!f.exists()) {
                f.createNewFile();
            }
            FileReader fr = new FileReader(ruta);
            BufferedReader br = new BufferedReader(fr);
            linea = br.readLine();
            while (!linea.equals("")) {
                lista.add(linea);
                IndiceLinea++;
                linea = br.readLine();
            }
            fr.close();
            br.close();
            f.delete();
            f.createNewFile();
            if (IndiceLinea<MaxLineas) {
                FileWriter fw = new FileWriter(ruta);
                BufferedWriter bw = new BufferedWriter(fw);
                for (String x :lista) {
                    bw.write(x);
                    bw.newLine();
                }
                bw.write(LineaInsertar);
                fw.close();
                bw.close();
                Escrito = true;
                direccion = Bloque+"."+IndiceLinea;
            }else{
            }
            Bloque++;
            ruta = inicio + Bloque + ext;
        }
        } catch (IOException ex) {
            Logger.getLogger(HacerDonación.class.getName()).log(Level.SEVERE, null, ex);
        }
        return (direccion);
    }
    
    public void InsertarIndexadoIndex(String llave, String direccion)
    {
        ArrayList<String> lista = new ArrayList<>();
        String ruta = "C:\\MEIA\\DonacionIndex.txt";
        String linea = "";
        File f = new File(ruta);
        try {
            if (!f.exists()) {
                f.createNewFile();
            }
            FileReader fr = new FileReader(ruta);
            BufferedReader br = new BufferedReader(fr);
            linea = br.readLine();
            while(!linea.equals("")){
                lista.add(linea);
                linea = br.readLine();
            }
            fr.close();
            br.close();
            f.delete();
            f.createNewFile();
            FileWriter fw = new FileWriter(ruta);
            BufferedWriter bw = new BufferedWriter(fw);
            for (String x : lista){
                bw.write(x);
                bw.newLine();
            }
            fw.write(llave+","+direccion);
            fw.close();
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(HacerDonación.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void ActualizarDescriptores()
    {
        int Bloque = 1;
        int registros = 0;
        String inicioDesc = "C:\\MEIA\\DonacionDescriptor_";
        String inicioFile = "C:\\MEIA\\Donacion_";
        String ext = ".txt";
        String rutaDesc = inicioDesc+Bloque+ext;
        String rutaFile = inicioFile+Bloque+ext;
        File fD = new File(rutaDesc);
        File fF = new File(rutaFile);
        FileReader filefr = null;
        BufferedReader filebr = null;
        FileWriter descfw = null;
        BufferedWriter descbw = null;
        String lineaFile = "";
        String adminuser = "";
        while(fF.exists()){
            try {
                filefr = new FileReader(rutaFile);
                filebr = new BufferedReader(filefr);
                lineaFile = filebr.readLine();
                while(!lineaFile.equals("")){
                    registros++;
                }
                filefr.close();
                filebr.close();
                if (fD.exists()) {
                    fD.delete();
                }
                fD.createNewFile();
                descfw = new FileWriter(rutaDesc);
                descbw = new BufferedWriter(descfw);
                String nombreArchivo = "Nombre del archivo:Donacion_"+Bloque+ext;
                String usuarioCreador = "Usuario creador:";
                File usuarios = new File("C:\\MEIA\\usuario.txt");
                if (usuarios.exists()) {
                    FileReader usuariofr = new FileReader(usuarios);
                    BufferedReader usuariosbr = new BufferedReader(usuariofr);
                    usuarioCreador += usuariosbr.readLine().split("\\,")[0];
                    usuariofr.close();
                    usuariosbr.close();
                }
                Date fdate = new Date();
                String fecha = "Fecha de creacion:"+ fdate.getDay() +"/"+ fdate.getMonth() +"/"+fdate.getYear();
                String cantidadregistros = "Cantidad de registros:" + registros;
                String cantidadregistrosactivos = "Cantidad de registros activos:" + registros;
                String cantidadregistrosinactivos = "Cantidad de registros inactivos:" + 0;
                String maxporbloquedato = "Maximos por bloque:" + 3;
                descbw.write(nombreArchivo);
                descbw.newLine();
                descbw.write(usuarioCreador);
                descbw.newLine();
                descbw.write(fecha);
                descbw.newLine();
                descbw.write(cantidadregistros);
                descbw.newLine();
                descbw.write(cantidadregistrosactivos);
                descbw.newLine();
                descbw.write(cantidadregistrosinactivos);
                descbw.newLine();
                descbw.write(maxporbloquedato);
                descbw.newLine();
                descfw.close();
                descbw.close();
            } catch (IOException ex) {
                Logger.getLogger(HacerDonación.class.getName()).log(Level.SEVERE, null, ex);
            }
            Bloque++;
        rutaDesc = inicioDesc+Bloque+ext;
        rutaFile = inicioFile+Bloque+ext;
        }
    }
    /**
     * @param args the command line arguments
     */ArrayList<String> Opciones = new ArrayList<String>();
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HacerDonación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HacerDonación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HacerDonación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HacerDonación.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HacerDonación().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDonar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcMateriales;
    private javax.swing.JTextArea taEvento;
    private javax.swing.JTextField tfDescripcion;
    private javax.swing.JTextField tfPeso;
    // End of variables declaration//GEN-END:variables
}
