/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import Clases.Backup;
import Clases.ArchivosIniciales;
import Clases.DatosUsuario;
import static Clases.DatosUsuario.DatosList;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import javax.swing.JOptionPane;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author josei
 */


public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfUsuario = new javax.swing.JTextField();
        btIniciar = new javax.swing.JButton();
        tfContrasena = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INICIAR SESIÓN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Usuario");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Contraseña");

        tfUsuario.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        btIniciar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btIniciar.setText("Iniciar Sesión");
        btIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btIniciarMouseClicked(evt);
            }
        });

        tfContrasena.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tfContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(btIniciar)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         File Carpeta = new File("C:\\MEIA");
        
        if (!Carpeta.exists())
        {
            Carpeta.mkdir();
            ArchivosIniciales a = new ArchivosIniciales();
            a.Creacion();
        }
        try {
                if (usuarios_esta_vacio() &&  bitacora_esta_vacio()) 
                {
                    //crear primer usuario admin
                    this.setVisible(false);
                    new CrearUsuario().setVisible(true);
                }
            } catch (IOException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_formWindowOpened

    private void btIniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btIniciarMouseClicked
        //Verificar que se llenen los campos de usuario y contraseña
        if ((tfUsuario.getText().equals(""))|| (tfContrasena.getPassword().length == 0 ))
        {
            JOptionPane.showMessageDialog(null, "Debe ingresar usuario y contraseña para continuar");
        }
        else
        {
            boolean UsuarioEncontrado = false;
            int linea1numero = 1, linea2numero = 1;
            String linealeida1 = "", linealeida2 ="";
            String ContrasenaIngreso = String.valueOf(tfContrasena.getPassword());
            try { //Se busca al usuario ingresado en el archivo de texto
                FileReader Bitacoratxt = new FileReader("C:/MEIA/bitacora.txt");
                BufferedReader UsuarioBitacora = new BufferedReader(Bitacoratxt);
                while (((linealeida1 = UsuarioBitacora.readLine()) != null)) {                    
                    if (linealeida1.contains(tfUsuario.getText())) 
                    { 
                        UsuarioEncontrado = true;
                        JOptionPane.showMessageDialog(null, "Se encontró al usuario");
                        break;
                    }
                    else
                    {
                        linea1numero++;
                    }
                }
                UsuarioBitacora.close();
                Bitacoratxt.close();
                if (UsuarioEncontrado) 
                {
                    this.setVisible(false);
                    IngresarSistema(linealeida1, ContrasenaIngreso);
                }
                else
                {
                    FileReader Usuariotxt = new FileReader("C:/MEIA/usuario.txt");
                BufferedReader UsuarioArchivo = new BufferedReader(Usuariotxt);
                while (((linealeida2 = UsuarioArchivo.readLine()) != null)) 
                {                    
                    if (linealeida2.contains(tfUsuario.getText())) 
                    { 
                        UsuarioEncontrado = true;
                        JOptionPane.showMessageDialog(null, "Se encontró al usuario");
                        break;
                    }
                    else
                    {
                        linea2numero++;
                    }
                }
                UsuarioArchivo.close();
                Usuariotxt.close();
                if(UsuarioEncontrado)
                {
                    this.setVisible(false);
                    IngresarSistema(linealeida2, ContrasenaIngreso);
                }
                else 
                {
                   JOptionPane.showMessageDialog(null, "No se encontró al usuario, contacte al administrador para registrarse");
                }
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
        }
        
    }//GEN-LAST:event_btIniciarMouseClicked
public boolean usuarios_esta_vacio()throws FileNotFoundException, IOException{
        String Cadena;
        FileReader archivo = new FileReader("C:\\MEIA\\usuario.txt");
        BufferedReader lector = new BufferedReader(archivo);
         Cadena = lector.readLine();
         lector.close();
         archivo.close();
         if (Cadena==null) {
            return true;
        }
         else
         {
             return false;
         }
    }


public boolean bitacora_esta_vacio()throws FileNotFoundException, IOException{
        String Cadena;
        FileReader archivo = new FileReader("C:\\MEIA\\bitacora.txt");
        BufferedReader lector = new BufferedReader(archivo);
         Cadena = lector.readLine();
         lector.close();
         archivo.close();
         if (Cadena==null) {
            return true;
        }
         else
         {
             return false;
         }
    }
public static void IngresarSistema (String UsuarioRegistro, String Contra)
{
    String[] CamposUsuario;
    CamposUsuario = UsuarioRegistro.split("\\|");
    if (CamposUsuario.length == 11) 
    {
        if (Contra.equals(CamposUsuario[3])) 
        {//password confirmada
            DatosList= CamposUsuario;
            if ((CamposUsuario[4]).equals("1"))
            {
                JOptionPane.showMessageDialog(null, "El usuario es administrador");
                
                new PanelAdmin().setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "El usuario no es administrador");
                new PanelUsuario().setVisible(true);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Contraseña inválida. \n  Intentelo de nuevo");
            new Login ().setVisible(true);
        }
    }
}
    /**
     * @param args the command line arguments
     */

public static String Usuario = "";
public static String Contrasena = "";
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btIniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField tfContrasena;
    private javax.swing.JTextField tfUsuario;
    // End of variables declaration//GEN-END:variables
}
