/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import static Clases.DatosMateriales.ArbolMateriales;
import static Clases.DatosMateriales.ContadorNodos;
import static Clases.DatosMateriales.ReporteMateriales;
import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;
import javax.swing.table.*;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Image;
import java.io.File;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author josei
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
        AgregarEncabezados();
        
    }
    public class Elemento
    {
        public String Nombre;
        public String Tipo;
        public String Imagen;
        public String Degradado;
        public Elemento(String Nombre,String Tipo, String Imagen,String Tiempo)
        {
            this.Nombre = Nombre;
            this.Tipo = Tipo;
            this.Imagen = Imagen;
            this.Degradado= Tiempo;
        }
    }
    
    public ArrayList MaterialesReportados()
    {
        ArrayList<Elemento> ListaMateriales = new ArrayList<Elemento>();
        for (String Linea : ReporteMateriales)
        {
            String[] Valores = Linea.split("\\|");
            Elemento Valor = new Elemento(Valores[0],Valores[1],Valores[2],Valores[3]);
            ListaMateriales.add(Valor);
        }
        return ListaMateriales;
    }
    public void AgregarFila()
    {
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jMateriales = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Materiales Registrados");

        jButton1.setText("cerrar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jMateriales);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    DefaultTableModel model;
    String Nombre = "";
    String Tipo = "";
    String Degradado = "";
    String Estado = "";
    String Imagen = "";
    public void AgregarEncabezados() {
        model = (DefaultTableModel) jMateriales.getModel();
        Object[] newIdentifiers = new Object[]{"Nombre", "Tipo", "Degradado", "Estado", "Imagen"};
        model.setColumnIdentifiers(newIdentifiers);
        jMateriales.setFillsViewportHeight(true);
        jMateriales.getColumn("Imagen").setCellRenderer(new CellRenderer());

    }

    class CellRenderer implements TableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable table,
                Object value,
                boolean isSelected,
                boolean hasFocus,
                int row,
                int column) {
            TableColumn tb = jMateriales.getColumn("Imagen");
            tb.setMaxWidth(60);
            tb.setMinWidth(60);
            jMateriales.setRowHeight(60);
            return (Component) value;
        }

    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ReporteMateriales.clear();
        LimpiarTabla();
        ObtenerArbol();
        int i=0;
        ArbolMateriales.Inorden();
        for(String Registro : ReporteMateriales)
        {
            String [] Campos = Registro.split("\\|");
            Nombre = Campos[0];
            Tipo = Campos[1];
            Imagen = Campos[2];
            Degradado =Campos[3];
            Estado = "Activo";
            JLabel ImagenLabel = new JLabel();
            ImageIcon Icono = new ImageIcon(Imagen);
            Image imag = Icono.getImage().getScaledInstance(60, 60, Image.SCALE_SMOOTH);
            ImagenLabel.setIcon(new ImageIcon(imag));
            model.addRow(new Object[]{Nombre,Tipo, Degradado, Estado,ImagenLabel});          
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }
      public void ObtenerArbol()
    {
        ContadorNodos=0;
        ArbolMateriales.Raiz = null;
        String linealeida1;
        try { //Se busca al usuario ingresado en el archivo de texto
                FileReader BitacoraMateriales = new FileReader("C:/MEIA/Materiales2.txt");
                BufferedReader MaterialesBitacora = new BufferedReader(BitacoraMateriales);
                while (((linealeida1 = MaterialesBitacora.readLine()) != null)) 
                {   
                    ContadorNodos++;
                    String[]Separar = linealeida1.split("\\|");
                    String RegistroPrevio = Separar[0]+"|"+Separar[3]+"|"+Separar[4]+"|"+Separar[5]+"|"+Separar[6]+"|"+Separar[7]+"|"+Separar[8]+"|"+Separar[9];
                    ArbolMateriales.AgregarNodo(RegistroPrevio);
                }
                MaterialesBitacora.close();
                BitacoraMateriales.close();                     
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,e.getMessage());
            }
    }

      public void LimpiarTabla()
      {
          DefaultTableModel Modelo = (DefaultTableModel) jMateriales.getModel();
          Modelo.setRowCount(0);
      }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable jMateriales;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
